UBER_PROJECT/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('uber/', include('uber.urls')),
]

uber/urls.py
from django.urls import path

from . import views

app_name = 'uber'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('userSignUp/', views.userSignUp, name='userSignUp'),
    path('userLogin/', views.userLogin, name='userLogin'),
    path('driverSignUp/', views.driverSignUp, name='driverSignUp'),
    path('driverLogin/', views.driverLogin, name='driverLogin'),
    path('userHomePage/<int:user_id>/', views.userHomePage, name='userHomePage'),
    path('driverHomePage/<int:driver_id>/', views.driverHomePage, name='driverHomePage'),
    path('newRequest/<int:user_id>/', views.newRequest, name='newRequest'),
    path('acceptRequest/<int:request_id>/<int:driver_id>/', views.acceptRequest, name="acceptRequest"),
]

uber/models.py
from django.db import models

# Create your models here.

uber/views.py
from django.http import HttpResponse, HttpResponseRedirect

from django.shortcuts import render, get_object_or_404
from django.urls import reverse
import cx_Oracle
from datetime import datetime, timedelta

def index(request):
	return render(request, 'uber/index.html')

def userSignUp(request):
	if request.method == 'POST':
		inputLst = []  # contains the received data from sing up form
		inputLst.append(request.POST['firstName'])
		inputLst[len(inputLst) - 1].strip()
		inputLst.append(request.POST['middleName'])
		inputLst[len(inputLst) - 1].strip()
		inputLst.append(request.POST['lastName'])
		inputLst[len(inputLst) - 1].strip()

		inputLst.append(request.POST['userName'])
		inputLst[len(inputLst) - 1].strip()
		inputLst.append(request.POST['passWord'])
		inputLst.append(request.POST['mobileNumber'])
		inputLst[len(inputLst) - 1].strip()

		inputLst.append(request.POST['email'])
		inputLst[len(inputLst) - 1].strip()
		inputLst.append(request.POST['birthDay'])
		inputLst.append(request.POST['street'])

		inputLst[len(inputLst) - 1].strip()
		inputLst.append(request.POST['city'])
		inputLst[len(inputLst) - 1].strip()
		inputLst.append(request.POST['postCode'])
		inputLst[len(inputLst) - 1].strip()

		errorLst = []

		# for first, middle and last name

		for i in range(3):
			inputLst[i] = inputLst[i].strip()
			flag = False
			errorLst.append('')
			name =''

			if i == 0:
				name = "First Name"
			elif i == 1:
				name = "Middle Name"
			else:
				name = "Last Name"

			for ch in inputLst[i]:
				if not ((ch >= 'a' and ch <= 'z') or (ch >= 'A' and ch <= 'Z')):
					flag = True
			if flag:
				errorLst[i] = "Invalid " + name

			if inputLst[i] and len(inputLst[i]) > 40:
				errorLst[i] = name + " too long!"

		#for username - 3      =================================

		errorLst.append('')

		connection = cx_Oracle.connect("SYSTEM/hello@localhost/orcl")
		cursor = connection.cursor()
		cursor.execute("SELECT * FROM APP_USER WHERE USERNAME = :username", username=inputLst[3])
		checkLst=[]
		for line in cursor:
			checkLst.append(line)

		if checkLst:
			errorLst[len(errorLst) - 1] = 'Username already taken!'
		elif len(inputLst[3]) > 40:
			errorLst[len(errorLst) - 1] = 'User Name too long!'

		# ================================== for passowrd - 4

		errorLst.append('')
		if len(inputLst[4]) > 40:
			errorLst[len(errorLst) - 1] = 'Password too long!'
		elif len(inputLst[4]) < 3:
			errorLst[len(errorLst) - 1] = 'Password too short!'

		#=================================== for mobile number - 5
		mobNumOk = True
		mobNumExist = False

		if len(inputLst[5]) != 11:
			errorLst.append("Invalide mobile number")
			mobNumOk = False
		elif inputLst[5][0] != '0' or inputLst[5][1] != '1':
			errorLst.append("Invalid mobile number")
			mobNumOk = False
		else:
			flag = True
			for i in range(2, 11):
				if not(inputLst[5][i] >= '0' and inputLst[5][i] <= '9'):
					flag = False

			if not flag:
				errorLst.append("Invalide mobile number")
				mobNumOk = False

		if mobNumOk:
			cursor.execute("SELECT * FROM MOBILE_NUMBERS WHERE MOBILE_NUMBER = :mob_num", mob_num=inputLst[5])
			checkLst = []
			for line in cursor:
				checkLst.append(line)

			if not checkLst or not checkLst[0][1]:
				if checkLst:
					mobNumExist = True
			else:
				errorLst.append("Mobile number already taken!")

		#=================================for email - 6 - not verified


		#=================================for birthday - 7 - not verified

		#=================================for location: street - 8, city - 9, postCode - 10
		#query with only street and city
		inputLst.append('')#for location ID

		errorLst.append('')
		errorLst.append('')
		errorLst.append('')
		if inputLst[8] and len(inputLst[8]) > 40:
			errorLst[len(errorLst) - 3] = 'Street name too long!'
		elif len(inputLst[9]) > 40:
			errorLst[len(errorLst) - 2] = 'City name too long!'
		elif inputLst[10] and len(inputLst[10]) > 10:
			errorLst[len(errorLst) - 1] = 'Postal Code too long!'

		isOK = True
		for val in errorLst:
			if val:
				isOK = False

		if not isOK:
			return render(request, 'uber/userSignUp.html', {
				'inputLst': inputLst,
				'errorLst': errorLst,
			})



		if inputLst[8]:
			cursor.execute("SELECT * FROM LOCATION WHERE CITY = :city AND STREET = :street", city=inputLst[9], street = inputLst[8])
			checkLst = []
			for line in cursor:
				checkLst.append(line)

			if checkLst:
				inputLst[len(inputLst) - 1] = checkLst[0][0]
			else:
				cursor.execute("INSERT INTO LOCATION(STREET, CITY) VALUES( :street, :city)", [inputLst[8], inputLst[9]])
				connection.commit()

				cursor.execute("SELECT * FROM LOCATION WHERE CITY = :city AND STREET = :street", city=inputLst[9],
							   street=inputLst[8])
				checkLst = []
				for line in cursor:
					checkLst.append(line)

				if checkLst:
					inputLst[len(inputLst) - 1] = checkLst[0][0]

		else:
			cursor.execute("SELECT * FROM LOCATION WHERE CITY = :city", city=inputLst[9])
			checkLst = []
			for line in cursor:
				checkLst.append(line)

			if checkLst:
				inputLst[len(inputLst) - 1] = checkLst[0][0]
			else:
				cursor.execute("INSERT INTO LOCATION(CITY) VALUES( :city)", city=inputLst[9])
				connection.commit()

				cursor.execute("SELECT * FROM LOCATION WHERE CITY = :city", city=inputLst[9])
				checkLst = []
				for line in cursor:
					checkLst.append(line)

				if checkLst:
					inputLst[len(inputLst) - 1] = checkLst[0][0]

		cursor.execute("INSERT INTO APP_USER(FIRST_NAME, MIDDLE_NAME, LAST_NAME, USERNAME, PASSWORD, EMAIL, DATE_OF_BIRTH, LOCATION_ID ) VALUES(:firstName, :middleName, :lastName, :userName, :passWord, :email, TO_DATE(:date_of_birth, 'YYYY-MM-DD'), :location_id)", [inputLst[0], inputLst[1], inputLst[2], inputLst[3], inputLst[4], inputLst[6], inputLst[7], inputLst[11]])


		connection.commit()

		cursor.execute("SELECT * FROM APP_USER WHERE USERNAME = :userName", userName=inputLst[3])

		checkLst = []
		for line in cursor:
			checkLst.append(line)

		userId = checkLst[0][0]

		if mobNumExist:
			cursor.execute("UPDATE MOBILE_NUMBERS SET USER_ID = :user_id WHERE MOBILE_NUMBER = : mobNum", [userId, inputLst[5]])
			connection.commit()
		else:
			cursor.execute("INSERT INTO MOBILE_NUMBERS(MOBILE_NUMBER, USER_ID) VALUES (:mobNum, :user_id)", [inputLst[5], userId])
			connection.commit()

		cursor.close()
		connection.close()
		return HttpResponseRedirect(reverse('uber:userLogin'))


	else:
		return render(request, 'uber/userSignUp.html')


def driverSignUp(request):
	if request.method == 'POST':
		inputLst = []  # contains the received data from sing up form
		inputLst.append(request.POST['firstName'])
		inputLst[len(inputLst) - 1].strip()
		inputLst.append(request.POST['middleName'])
		inputLst[len(inputLst) - 1].strip()
		inputLst.append(request.POST['lastName'])
		inputLst[len(inputLst) - 1].strip()

		inputLst.append(request.POST['userName'])
		inputLst[len(inputLst) - 1].strip()
		inputLst.append(request.POST['passWord'])
		inputLst.append(request.POST['mobileNumber'])
		inputLst[len(inputLst) - 1].strip()

		inputLst.append(request.POST['email'])
		inputLst[len(inputLst) - 1].strip()
		inputLst.append(request.POST['birthDay'])
		inputLst.append(request.POST['street'])

		inputLst[len(inputLst) - 1].strip()
		inputLst.append(request.POST['city'])
		inputLst[len(inputLst) - 1].strip()
		inputLst.append(request.POST['postCode'])
		inputLst[len(inputLst) - 1].strip()

		errorLst = []

		# for first, middle and last name

		for i in range(3):
			inputLst[i] = inputLst[i].strip()
			flag = False
			errorLst.append('')
			name =''

			if i == 0:
				name = "First Name"
			elif i == 1:
				name = "Middle Name"
			else:
				name = "Last Name"

			for ch in inputLst[i]:
				if not ((ch >= 'a' and ch <= 'z') or (ch >= 'A' and ch <= 'Z')):
					flag = True
			if flag:
				errorLst[i] = "Invalid " + name

			if inputLst[i] and len(inputLst[i]) > 40:
				errorLst[i] = name + " too long!"

		#for username - 3      =================================

		errorLst.append('')

		connection = cx_Oracle.connect("SYSTEM/hello@localhost/orcl")
		cursor = connection.cursor()
		cursor.execute("SELECT * FROM DRIVER WHERE USERNAME = :username", username=inputLst[3])
		checkLst=[]
		for line in cursor:
			checkLst.append(line)

		if checkLst:
			errorLst[len(errorLst) - 1] = 'Username already taken!'
		elif len(inputLst[3]) > 40:
			errorLst[len(errorLst) - 1] = 'User Name too long!'

		# ================================== for passowrd - 4

		errorLst.append('')
		if len(inputLst[4]) > 40:
			errorLst[len(errorLst) - 1] = 'Password too long!'
		elif len(inputLst[4]) < 3:
			errorLst[len(errorLst) - 1] = 'Password too short!'

		#=================================== for mobile number - 5
		mobNumOk = True
		mobNumExist = False

		if len(inputLst[5]) != 11:
			errorLst.append("Invalide mobile number")
			mobNumOk = False
		elif inputLst[5][0] != '0' or inputLst[5][1] != '1':
			errorLst.append("Invalid mobile number")
			mobNumOk = False
		else:
			flag = True
			for i in range(2, 11):
				if not(inputLst[5][i] >= '0' and inputLst[5][i] <= '9'):
					flag = False

			if not flag:
				errorLst.append("Invalide mobile number")
				mobNumOk = False

		if mobNumOk:
			cursor.execute("SELECT * FROM MOBILE_NUMBERS WHERE MOBILE_NUMBER = :mob_num", mob_num=inputLst[5])
			checkLst = []
			for line in cursor:
				checkLst.append(line)

			if not checkLst or not checkLst[0][2]:
				if checkLst:
					mobNumExist = True
			else:
				errorLst.append("Mobile number already taken!")

		#=================================for email - 6 - not verified


		#=================================for birthday - 7 - not verified

		#=================================for location: street - 8, city - 9, postCode - 10
		#query with only street and city
		inputLst.append('')#for location ID

		errorLst.append('')
		errorLst.append('')
		errorLst.append('')
		if inputLst[8] and len(inputLst[8]) > 40:
			errorLst[len(errorLst) - 3] = 'Street name too long!'

uber/templates/uber/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    {% block Style %}
        <style type="text/css">

            body {
                background: #FDFDFE;
            }

            .topnav {
                background: #5dd4ee;
                overflow: hidden;
            }

            .topnav a {
                float: left;
                color: #000;
                text-align: center;
                padding: 15px 15px;
                text-decoration: none;

                font-size: 150%;
                font-family: sans-serif;
                font-weight: bold;
            }

            .topnav a:hover {
                background: #333;
                color: #f2f2f2;
            }

            header{
                text-align: center;
            }

            #forForm {
                display: block;
                border: 1px solid black;
                font-size: 125%;
                background: #c1c8d4;
            }

            #forForm input {
                display: block;
            }

            #forForm input[type=submit] {
                font-size: 120%;
                border-radius: 5px;
                background: #5dd4ee;
                display: block;


            }

            #forForm input[type=submit]:hover {
                background-color: #333333;
                color:#FFF;
            }

        </style>
    {% endblock %}

</head>
<body>

    {% comment %}<header>
        <h1 style="margin-bottom: 5px; margin-top:5px; font-family: sans-serif;">UBER</h1>
    </header>{% endcomment %}


{% block body%}
{% endblock %}

</body>
</html>

uber/templates/uber/driverLogin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Driver Login</title>
</head>
<body onload="reset()">

{% extends 'uber/base.html' %}
{% block body %}

     <div class = "topnav">
        <a href="{%  url 'uber:index' %}">HOME</a>
    </div>
    <br><br><br>

    <section id = "forForm">
        <h3 align="center">LOG IN FORM</h3>

        {% if errorLst %}
            {% for error in errorLst %}
                {% if error %}
                    <p>{{ error }}</p>
                {% endif %}
            {% endfor %}
        {% endif %}




        <form action="{% url 'uber:driverLogin' %}" method="post">
            {% csrf_token %}
            <label id = "label1" for="userName">Username:</label>
                {% if errorLst %}
                    <input type = "text" name="userName" id = "userName" value = "{{ inputLst.0 }}" required>
                {% else %}
                    <input type = "text" name="userName" id = "userName1" required>
                {% endif %}
            <br>

            <label> Password:
                {% if errorLst %}
                    <input type = "password" name="passWord" value = "{{ inputLst.1 }}" required>
                {% else %}
                    <input type = "password" name="passWord" required>
                {% endif %}
            </label>
            <br>
            <label id="label2">Use mobile number to log in</label>
            <input type = "checkbox" id = "check1" onclick="Flip()">
            <br>

            <input type = "submit" value="Log In">

        </form>

    </section>



    <script type="text/javascript">
        function Flip() {
            var labelText1 = document.getElementById("label1").textContent;
            if (labelText1 == "Username:") {

                document.getElementById("label1").textContent = "Mobile Number:";

                {% if errorLst %}
                    document.getElementById("userName").setAttribute('name', 'mobileNumber');
                {% else %}
                    document.getElementById("userName1").setAttribute('name', 'mobileNumber');
                {% endif %}
            }
            else {
                document.getElementById("label1").textContent="Username:";
                {% if errorLst %}
                    document.getElementById("userName").setAttribute('name', 'userName');
                {% else %}
                    document.getElementById("userName1").setAttribute('name', 'userName');
                {% endif %}
            }

        }

        function reset() {
            {% if asUser == "mobileNumber" %}
                document.getElementById("label1").textContent="Mobile Number:";
                document.getElementById("check1").checked = true;
                {% if errorLst %}
                    document.getElementById("userName").setAttribute('name', 'mobileNumber');
                {% else %}
                    document.getElementById("userName1").setAttribute('name', 'mobileNumber');
                {% endif %}

            {% else %}

                document.getElementById("label1").textContent="Username:";
                document.getElementById("check1").checked = false;
                {% if errorLst %}
                    document.getElementById("userName").setAttribute('name', 'userName');
                {% else %}
                    document.getElementById("userName1").setAttribute('name', 'userName');
                {% endif %}

            {% endif %}

        }

    </script>
{% endblock %}

</body>
</html>

uber/templates/uber/driverSignUp.html
<!DOCTYPE html>
<html>
<head>
	<title>Sign Up</title>
</head>
<body>

{% extends 'uber/base.html' %}


{% block body %}

     <div class = "topnav">
        <a href="{%  url 'uber:index' %}">HOME</a>
    </div>
    <br><br><br>

    <section id="forForm">


        {% if errorLst %}
            {% for error in errorLst %}
                {% if error %}
                    <p> {{ error }}</p>
                {% endif %}
            {% endfor %}
        {% endif %}


        <section id = "signUp">

            <form action = "{% url 'uber:driverSignUp' %}" method="post">
                {% csrf_token %}
                <label> First Name:
                    {% if errorLst %}
                        <input type = "text" name="firstName" value = "{{ inputLst.0 }}" required>
                    {% else %}
                        <input type = "text" name="firstName" required>
                    {% endif %}

                </label>
                <label> Middle Name:
                    {% if errorLst %}
                        <input type = "text" name="middleName" value = "{{ inputLst.1 }}">
                    {% else %}
                        <input type = "text" name="middleName">
                    {% endif %}
                </label>
                <label> Last Name:
                    {% if errorLst %}
                        <input type = "text" name="lastName" value = "{{ inputLst.2 }}">
                    {% else %}
                        <input type = "text" name="lastName">
                    {% endif %}
                </label>

                <label>Username:
                    {% if errorLst %}
                        <input type = "text" name="userName" value = "{{ inputLst.3 }}" required>
                    {% else %}
                        <input type = "text" name="userName" required>
                    {% endif %}
                </label>

                <label> Password:
                    {% if errorLst %}
                        <input type = "password" name="passWord" value = "{{ inputLst.4 }}" required>
                    {% else %}
                        <input type = "password" name="passWord" required>
                    {% endif %}
                </label>

                <label> Mobile Number:
                    {% if errorLst %}
                        <input type = "text" name="mobileNumber" value = "{{ inputLst.5 }}" required>
                    {% else %}
                        <input type = "text" name="mobileNumber" required>
                    {% endif %}
                </label>

                <label> Email:
                    {% if errorLst %}
                        <input type = "email" name="email" value = "{{ inputLst.6 }}" required>
                    {% else %}
                        <input type = "email" name="email" required>
                    {% endif %}
                </label>

                <label> Date of Birth:
                    {% if errorLst %}
                        <input type = "date" name="birthDay" value = "{{ inputLst.7 }}" required>
                    {% else %}
                        <input type = "date" name="birthDay" required>
                    {% endif %}
                </label>
                <label> Street:
                    {% if errorLst %}
                        <input type = "text" name="street" value = "{{ inputLst.8 }}">
                    {% else %}
                        <input type = "text" name="street">
                    {% endif %}
                </label>
                <label> City:
                    {% if errorLst %}
                        <input type = "text" name="city" value = "{{ inputLst.9 }}" required>
                    {% else %}
                        <input type = "text" name="city" required>
                    {% endif %}
                </label>
                <label> Postal Code:
                    {% if errorLst %}
                        <input type = "text" name="postCode" value = "{{ inputLst.10 }}">
                    {% else %}
                        <input type = "text" name="postCode">
                    {% endif %}
                </label>


                <input type ="submit" id="submit" value="Sign Up">


            </form>

        </section>
    </section>
{% endblock %}

</body>
</html>

uber/templates/uber/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
    <title>UBER</title>


</head>
<body>

{% extends 'uber/base.html' %}


{% block body %}

     <div class = "topnav">
        <a href="{%  url 'uber:index' %}">HOME</a>
    </div>
    <br><br><br>

    <section id="forForm">

        <div style="margin-left: 30%;">

        <p> I am a
            <label> User <input type = "radio" name = "userType" id = "useR" checked> </label>
            <label> Driver <input type = "radio" name = "userType" id = "driveR"> </label>
        </p>
        </div>
        <br>



        <section id = "forUser" onsubmit="RadioValue()">

            <form action = "" method="get" id="logIN">
                {% csrf_token %}
                <input style="display: inline-block;margin-left: 40%;" type = "submit" value = "Log In" id = "lInput">

            </form>

        </section>

        <br><br>

        <section id = "forDriver" onsubmit="RadioValue()">

            <form action = "" method="get" id="signUP">
                {% csrf_token %}
                <input style="display: inline-block; margin-left: 40%;"type = "submit" value = "Sign Up" id = "sInput">

            </form>

        </section>
    </section>


	<script type="text/javascript">
		function RadioValue() {
			if(document.getElementById("useR").checked) {
				document.getElementById("logIN").action = "{% url 'uber:userLogin' %}";
				document.getElementById("signUP").action = "{% url 'uber:userSignUp' %}";
			}
			else if (document.getElementById("driveR").checked) {
				document.getElementById("logIN").action = "{% url 'uber:driverLogin' %}";
				document.getElementById("signUP").action = "{% url 'uber:driverSignUp' %}";
			}
		}
		
	</script>

{% endblock %}

</body>
</html>

uber/templates/uber/userHomePage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome!</title>
    <style type="text/css">
        label, input {
            margin-left: 40%;
        }
        input[type=submit] {
            margin-left: 60%;
        }
        #pickUP {
            display: inline-block;

            margin-right: 5%;
            width: 40%;
        }
        #dest{
            display: inline-block;
            width: 40%;
        }

    </style>
</head>
<body>


{% extends 'uber/base.html' %}
{% block body %}

    <div class="topnav">
        <a href="#">HOME</a>
        <a href="#" style="float: right;"> {{ userInfo.1 }}</a>
        <a href="#" style="float: right;">LOG OUT</a>

    </div>
    <br><br><br>

    <section id="forForm">
    <form style="float: right;" action="{% url 'uber:userHomePage' userInfo.0 %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Refresh">
    </form>

    {% if requestData %}

        <h2 align="center"> Ride Info: </h2>

        <p style="font-size: 150%; font-weight: bolder;"> From:</p>
        {% if requestData.9.0 %}
            <p>STREET: {{ requestData.9.0 }}</p>
        {% endif %}
        <p> CITY: {{ requestData.9.1 }}</p>


        <p style="font-size: 150%; font-weight: bolder;"> Destination:</p>
        {% if requestData.10.0 %}
            <p>STREET: {{ requestData.10.0 }}</p>
        {% endif %}
        <p> CITY: {{ requestData.10.1 }}</p>


        <p style="font-size: 150%; font-weight: bolder;"> Approximate Fare: {{ requestData.5 }}</p>
        <br>

        {% if riderInfo %}
            <p> We have got a rider for you!</p>
            <details>
                    <summary>Show Rider Info</summary>
                    <p>Name: {{ riderInfo.1 }} {{ riderInfo.2 }} {{ riderInfo.3 }}</p>
                    {% if riderInfo.8 %}
                        <p>Rating: {{ riderInfo.7 }} / {{ riderInfo.8 }}</p>
                    {% else %}
                        <p>New User</p>
                    {% endif %}
                    <p> Mobile Number(s): </p>
                    {% for num in riderInfo.12 %}
                        <p>{{ num }}</p>
                    {% endfor %}
                </details>
        {% else %}
            <p>Please wait until we find a rider for you!</p>

        {% endif %}

    {% else %}
        <h2 align="center"> Need a ride?</h2>
        {% for error in errorLst %}
            <p>{{ error }}</p>
        {% endfor %}

        <form action="{% url 'uber:newRequest' userInfo.0 %}" method="post">
            {% csrf_token %}
            <div id = "pickUP">
            <label> Pick up point: <br> <br>
                <label> Street:
                    {% if errorLst %}
                        <input type="text" name="street1" value="{{ pickupLoc.0 }}">
                    {% else %}
                        <input type = "text" name ="street1">
                    {% endif %}
                </label>
                <label> City:
                    {% if errorLst %}
                        <input type = "text" name="city1" value="{{ pickupLoc.1 }}" required>
                    {% else %}
                        <input type="text" name="city1" required>
                    {% endif %}
                </label>
                <label> Postal Code:
                    <input type="text" name="postCode1" disabled>
                </label>
            </label>


            </div>
            <div id = "dest">
            <label> Destination: <br> <br>
                <label> Street:
                    {% if errorLst %}
                        <input type="text" name="street2" value="{{ destLoc.0 }}">
                    {% else %}
                        <input type = "text" name ="street2">
                    {% endif %}
                </label>
                <label> City:
                    {% if errorLst %}
                        <input type = "text" name="city2" value="{{ destLoc.1 }}" required>
                    {% else %}
                        <input type="text" name="city2" required>
                    {% endif %}
                </label>
                <label> Postal Code:
                    <input type="text" name="postCode2" disabled>
                </label>

            </label>

            </div>
            <br><br> <br>
             <input align="center" style="margin-left: 30%;" type ="submit" value = "Submit Request">

        </form>

    {% endif %}
    </section>


{% endblock %}

</body>
</html>

uber/templates/uber/userSignUp.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
	<title>Sign Up</title>

</head>
<body>

{% extends 'uber/base.html' %}


{% block body %}

     <div class = "topnav">
        <a href="{%  url 'uber:index' %}">HOME</a>
    </div>
    <br><br><br>

    <section id="forForm">


        {% if errorLst %}
            {% for error in errorLst %}
                {% if error %}
                    <p> {{ error }}</p>
                {% endif %}
            {% endfor %}
        {% endif %}


        <section id = "signUp">

            <form action = "{% url 'uber:userSignUp' %}" method="post">
                {% csrf_token %}
                <label> First Name:
                    {% if errorLst %}
                        <input type = "text" name="firstName" value = "{{ inputLst.0 }}" required>
                    {% else %}
                        <input type = "text" name="firstName" required>
                    {% endif %}

                </label>
                <label> Middle Name:
                    {% if errorLst %}
                        <input type = "text" name="middleName" value = "{{ inputLst.1 }}">
                    {% else %}
                        <input type = "text" name="middleName">
                    {% endif %}
                </label>
                <label> Last Name:
                    {% if errorLst %}
                        <input type = "text" name="lastName" value = "{{ inputLst.2 }}">
                    {% else %}
                        <input type = "text" name="lastName">
                    {% endif %}
                </label>

                <label>Username:
                    {% if errorLst %}
                        <input type = "text" name="userName" value = "{{ inputLst.3 }}" required>
                    {% else %}
                        <input type = "text" name="userName" required>
                    {% endif %}
                </label>

                <label> Password:
                    {% if errorLst %}
                        <input type = "password" name="passWord" value = "{{ inputLst.4 }}" required>
                    {% else %}
                        <input type = "password" name="passWord" required>
                    {% endif %}
                </label>

                <label> Mobile Number:
                    {% if errorLst %}
                        <input type = "text" name="mobileNumber" value = "{{ inputLst.5 }}" required>
                    {% else %}
                        <input type = "text" name="mobileNumber" required>
                    {% endif %}
                </label>

                <label> Email:
                    {% if errorLst %}
                        <input type = "email" name="email" value = "{{ inputLst.6 }}" required>
                    {% else %}
                        <input type = "email" name="email" required>
                    {% endif %}
                </label>

                <label> Date of Birth:
                    {% if errorLst %}
                        <input type = "date" name="birthDay" value = "{{ inputLst.7 }}" required>
                    {% else %}
                        <input type = "date" name="birthDay" required>
                    {% endif %}
                </label>
                <label> Street:
                    {% if errorLst %}
                        <input type = "text" name="street" value = "{{ inputLst.8 }}">
                    {% else %}
                        <input type = "text" name="street">
                    {% endif %}
                </label>
                <label> City:
                    {% if errorLst %}
                        <input type = "text" name="city" value = "{{ inputLst.9 }}" required>
                    {% else %}
                        <input type = "text" name="city" required>
                    {% endif %}
                </label>
                <label> Postal Code:
                    {% if errorLst %}
                        <input type = "text" name="postCode" value = "{{ inputLst.10 }}">
                    {% else %}
                        <input type = "text" name="postCode">
                    {% endif %}
                </label>


                <input type ="submit" id="submit" value="Sign Up">


            </form>

        </section>
    </section>

{% endblock %}

</body>
</html>